version: '2.0'

services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 3000:80
      - 80:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf            #映射nginx的配置文件到容器里
      - ./nginx/logs/:/var/log/nginx/
  mysql:
    image: mysql:5.6
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "961007"